import store from "@/store";

export default [
    {
        path: "admins",
        name: "AdminadminsList",
        component: () => import("@/views/admins/list"),
        meta: { title: "管理员列表", authLogin: true },
    },
    {
        path: "adminsadd",
        name: "AdminadminsAdd",
        component: () => import("@/views/admins/add"),
        meta: { title: "添加管理员", authLogin: true },
    },
    {
        path: "adminsupdt",
        name: "AdminadminsUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/admins/updt"),
        meta: { title: "编辑管理员", authLogin: true },
    },
    {
        path: "adminsupdtself",
        name: "AdminadminsUpdtSelf",
        props: (route) => ({ id: store.state.user.session.id }),
        component: () => import("@/views/admins/updt"),
        meta: { title: "编辑管理员", authLogin: true },
    },
    {
        path: "wxuser",
        name: "AdminwxuserList",
        component: () => import("@/views/wxuser/list"),
        meta: { title: "微信用户列表", authLogin: true },
    },
    {
        path: "wxuseradd",
        name: "AdminwxuserAdd",
        component: () => import("@/views/wxuser/add"),
        meta: { title: "添加微信用户", authLogin: true },
    },
    {
        path: "wxuserupdt",
        name: "AdminwxuserUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/wxuser/updt"),
        meta: { title: "编辑微信用户", authLogin: true },
    },
    {
        path: "changguan",
        name: "AdminchangguanList",
        component: () => import("@/views/changguan/list"),
        meta: { title: "场馆列表", authLogin: true },
    },
    {
        path: "changguan_tianjiaren",
        name: "AdminchangguanListtianjiaren",
        component: () => import("@/views/changguan/list-tianjiaren"),
        meta: { title: "场馆列表", authLogin: true },
    },
    {
        path: "changguanadd",
        name: "AdminchangguanAdd",
        component: () => import("@/views/changguan/add"),
        meta: { title: "添加场馆", authLogin: true },
    },
    {
        path: "changguanupdt",
        name: "AdminchangguanUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/changguan/updt"),
        meta: { title: "编辑场馆", authLogin: true },
    },
    {
        path: "changguandetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminchangguanDetail",
        component: () => import("@/views/changguan/detail"),
        meta: { title: "场馆详情", authLogin: true },
    },
    {
        path: "kecheng",
        name: "AdminkechengList",
        component: () => import("@/views/kecheng/list"),
        meta: { title: "课程列表", authLogin: true },
    },
    {
        path: "kecheng_tianjiaren",
        name: "AdminkechengListtianjiaren",
        component: () => import("@/views/kecheng/list-tianjiaren"),
        meta: { title: "课程列表", authLogin: true },
    },
    {
        path: "kechengadd",
        name: "AdminkechengAdd",
        component: () => import("@/views/kecheng/add"),
        meta: { title: "添加课程", authLogin: true },
    },
    {
        path: "kechengupdt",
        name: "AdminkechengUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/kecheng/updt"),
        meta: { title: "编辑课程", authLogin: true },
    },
    {
        path: "kechengdetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminkechengDetail",
        component: () => import("@/views/kecheng/detail"),
        meta: { title: "课程详情", authLogin: true },
    },
    {
        path: "yuyue",
        name: "AdminyuyueList",
        component: () => import("@/views/yuyue/list"),
        meta: { title: "预约列表", authLogin: true },
    },
    {
        path: "yuyue_tianjiaren",
        name: "AdminyuyueListtianjiaren",
        component: () => import("@/views/yuyue/list-tianjiaren"),
        meta: { title: "预约列表", authLogin: true },
    },
    {
        path: "yuyue_yuyueren",
        name: "AdminyuyueListyuyueren",
        component: () => import("@/views/yuyue/list-yuyueren"),
        meta: { title: "预约列表", authLogin: true },
    },
    {
        path: "yuyueadd",
        name: "AdminyuyueAdd",
        component: () => import("@/views/yuyue/add"),
        meta: { title: "添加预约", authLogin: true },
    },
    {
        path: "yuyueupdt",
        name: "AdminyuyueUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/yuyue/updt"),
        meta: { title: "编辑预约", authLogin: true },
    },
    {
        path: "yuyuedetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminyuyueDetail",
        component: () => import("@/views/yuyue/detail"),
        meta: { title: "预约详情", authLogin: true },
    },
    {
        path: "kechengleixing",
        name: "AdminkechengleixingList",
        component: () => import("@/views/kechengleixing/list"),
        meta: { title: "课程类型列表", authLogin: true },
    },
    {
        path: "kechengleixingadd",
        name: "AdminkechengleixingAdd",
        component: () => import("@/views/kechengleixing/add"),
        meta: { title: "添加课程类型", authLogin: true },
    },
    {
        path: "kechengleixingupdt",
        name: "AdminkechengleixingUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/kechengleixing/updt"),
        meta: { title: "编辑课程类型", authLogin: true },
    },
    {
        path: "quxiaoyuyue",
        name: "AdminquxiaoyuyueList",
        component: () => import("@/views/quxiaoyuyue/list"),
        meta: { title: "取消预约列表", authLogin: true },
    },
    {
        path: "quxiaoyuyue_tianjiaren",
        name: "AdminquxiaoyuyueListtianjiaren",
        component: () => import("@/views/quxiaoyuyue/list-tianjiaren"),
        meta: { title: "取消预约列表", authLogin: true },
    },
    {
        path: "quxiaoyuyue_quxiaoren",
        name: "AdminquxiaoyuyueListquxiaoren",
        component: () => import("@/views/quxiaoyuyue/list-quxiaoren"),
        meta: { title: "取消预约列表", authLogin: true },
    },
    {
        path: "quxiaoyuyueadd",
        name: "AdminquxiaoyuyueAdd",
        component: () => import("@/views/quxiaoyuyue/add"),
        meta: { title: "添加取消预约", authLogin: true },
    },
    {
        path: "quxiaoyuyueupdt",
        name: "AdminquxiaoyuyueUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/quxiaoyuyue/updt"),
        meta: { title: "编辑取消预约", authLogin: true },
    },
    {
        path: "quxiaoyuyuedetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminquxiaoyuyueDetail",
        component: () => import("@/views/quxiaoyuyue/detail"),
        meta: { title: "取消预约详情", authLogin: true },
    },
    {
        path: "bmizhi",
        name: "AdminbmizhiList",
        component: () => import("@/views/bmizhi/list"),
        meta: { title: "BMI值列表", authLogin: true },
    },
    {
        path: "bmizhi_tianjiaren",
        name: "AdminbmizhiListtianjiaren",
        component: () => import("@/views/bmizhi/list-tianjiaren"),
        meta: { title: "BMI值列表", authLogin: true },
    },
    {
        path: "bmizhiadd",
        name: "AdminbmizhiAdd",
        component: () => import("@/views/bmizhi/add"),
        meta: { title: "添加BMI值", authLogin: true },
    },
    {
        path: "bmizhiupdt",
        name: "AdminbmizhiUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/bmizhi/updt"),
        meta: { title: "编辑BMI值", authLogin: true },
    },
    {
        path: "bmizhidetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminbmizhiDetail",
        component: () => import("@/views/bmizhi/detail"),
        meta: { title: "BMI值详情", authLogin: true },
    },
    {
        path: "lunbotu",
        name: "AdminlunbotuList",
        component: () => import("@/views/lunbotu/list"),
        meta: { title: "轮播图列表", authLogin: true },
    },
    {
        path: "lunbotuadd",
        name: "AdminlunbotuAdd",
        component: () => import("@/views/lunbotu/add"),
        meta: { title: "添加轮播图", authLogin: true },
    },
    {
        path: "lunbotuupdt",
        name: "AdminlunbotuUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/lunbotu/updt"),
        meta: { title: "编辑轮播图", authLogin: true },
    },
];
